name: Publish Website
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun i --frozen-lockfile
      - name: Build Project
        run: bun run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
